datasources:
  default:
    url: jdbc:h2:mem:TestadorDB;MVCC=TRUE;LOCK_TIMEOUT=10000;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE-DROP
    dialect: H2